name: Build, test and check format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build package
        run: yarn compile

      - name: Test the package (Linux)
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: Test the package (Others)
        run: yarn test
        if: runner.os != 'Linux'

      - name: Check file formatting
        run: yarn format:check
