name: GitHub release and VSCode Extension publishing

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"
      - "v*.*.*-*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 20.x
          cache: yarn
      - run: yarn install --immutable
      - run: yarn run compile
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: yarn deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
