name: GitHub release and VSCode Extension publishing

on:
  push:
    branches:
      - main

jobs:
  create_github_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  publish:
    runs-on: ubuntu-latest
    needs:
      - create_github_release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 20.x
      - run: yarn install --frozen-lockfile
      - run: yarn run compile
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: yarn deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
