name: GitHub release and VSCode Extension publishing

on:
  workflow_run:
    workflows: ["Build, test and check format"]
    branch:
      - main
    types:
      - completed

  # push:
  #   tags:
  #     - "v*.*.*"
  #     - "v*.*.*-*"
  #     - "v*.*.*-*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 20.x
          cache: yarn
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: VSIX
      #     path: "*.vsix"
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: "*.vsix"
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build package
        run: npx vsce package
      - name: Publish
        run: yarn deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
